Add IoT wifi support
AlexandrErohin/TP-Link-Archer-C6U pull request #4
Opened 2023-12-27 00:23 UTC by adamgross42

Enum values and README updates

I am surprised that this required the "guest" value on https://github.com/AlexandrErohin/TP-Link-Archer-C6U/blob/main/tplinkrouterc6u/client.py#L57 - but it seems to work still.

2023-12-27 00:32 UTC, adamgross42 commented
I'm not sure how to handle the situation where these IoT fields aren't supported on a device model - there may need to be None-checks in a few places.

2023-12-27 23:39 UTC, adamgross42 commented
I attempted to rebase on the latest 'main' branch, duplicate commits may have to be squashed.

2023-12-28 07:48 UTC, AlexandrErohin commented
@adamgross42 Thanks!
Could you check my comment for making iot_2g_enable bool | None

2023-12-28 08:06 UTC, adamgross42 commented
Hmm, I don't see any comments in this PR - maybe the review needs to be submitted for me to see them?

2023-12-28 08:10 UTC, AlexandrErohin requested changes

2023-12-28 08:10 UTC, AlexandrErohin commented on tplinkrouterc6u/client.py
> +        status.iot_2g_enable = data.get('iot_2g_enable') == 'on'
As IoT is supported not by every router, it is better to make status.iot_2g_enable = data.get('iot_2g_enable') == 'on' if data.get('iot_2g_enable') is not None else None

2023-12-28 18:54 UTC, adamgross42 commented on tplinkrouterc6u/client.py
> +        status.iot_2g_enable = data.get('iot_2g_enable') == 'on'
I can add that in.

Should I also change these two lines to add ` | None`?

https://github.com/AlexandrErohin/TP-Link-Archer-C6U/blob/dccfb505713c1d3ae9f54d4cfa17b5c5eebad5dc/tplinkrouterc6u/dataclass.py#L31-L32

2023-12-28 18:55 UTC, adamgross42 commented on tplinkrouterc6u/client.py
> +        status.iot_2g_enable = data.get('iot_2g_enable') == 'on'
Ah, the typechecker tells me yes, I'll add that too :)

2024-01-10 04:54 UTC, adamgross42 commented
@AlexandrErohin , what are your thoughts on this?  Are you able to test this locally to confirm the null checks work for a router that doesn't have the IoT network?

2024-01-10 07:57 UTC, AlexandrErohin commented
@adamgross42 Hi! Thank you for this PR. Unfortunately, I didnt have time to test it on my router. Give me a week please to check this.

2024-01-10 11:45 UTC, merged

2024-01-10 15:50 UTC, AlexandrErohin commented
@adamgross42 I have released it https://pypi.org/project/tplinkrouterc6u/1.3.0/
Thank you!